# Generated by Django 2.2 on 2020-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_profilefeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeed',
            old_name='User_profile',
            new_name='user_profile',
        ),
    ]
